### PR TITLE
Fix the multi-voice, the overlapping problem of two adjacent voices

### PR DESCRIPTION
**Pull request by zhwei8090**
image

But it caused a new problem, which I think is the problem of Guido library：

image
[test_6.xml.zip](https://github.com/grame-cncm/libmusicxml/files/8956438/test_6.xml.zip)

### CODE REVIEW

**Comment by dfober** [comment]
note that with guido you could solve the collision issue using dx with the \acc tag i.e:
`\noteFormat<dx=2>\acc<dx=-2>( g&1/16)`
image
Don't know if that can be solved at musicxml level in a general way.

**Comment by arshiacont** [comment]
This is really great! Thanks @zhwei8090 !
@dfober We have a [complicated] way of inferring the dx from multi-voice XMLs in this case. 
It seems like I have been ignoring this when there is no _offset_ on the element! The correction makes sense for notes but I am wondering if we call this method for other elements (such as wedges) and whether it'd lead to bad positioning. It's however good for merge. If we encounter such cases we should probably use a separate method for that.

**Comment by arshiacont** [comment]
@dfober my previous message slipped too fast: In @zhwei8090 's fix, we are using the NoteFormat. Are you suggesting that the `\acc` should follow the same `dx` as in the associated noteFormat?

**Comment by zhwei8090** [comment]
@dfober @arshiacont Yes, mainly to fix multi-voice no offset, missing noteFormat dx issue

**Comment by dfober** [comment]
> Are you suggesting that the `\acc` should follow the same `dx` as in the associated noteFormat?

@arshiacont yes, that's one way to solve the collision. But it's probably difficult to solve this issue in a general way, it requires to have a global view on the context (are there other accidentals, etc.). 
I agree regarding the fact that this is an issue that should be posted to guido (including note collision detection in multi voice context). 
I'll first try to solve that at guido level.

**Comment by zhwei8090** [comment]
@dfober  Yes, my idea is to judge based on the context. If there is a test sample, you can try it. Because of the time, we will use this solution for the time being.

**Comment by dfober** [comment]
ok, I'll leave the merge pending for now. If there is a solution with guido, it will not be necessary. I'll keep you informed (but it may take a bit time).

**Comment by zhwei8090** [comment]
ok

**Comment by dfober** [comment]
I've pushed a new version of the guido engine that can fix the multi-voices collision issue with an [example](https://github.com/grame-cncm/guidolib/blob/dev/gmn-examples/new-tags-v1.76/voiceCollisions.gmn) of use.
Could you check?

**Comment by zhwei8090** [comment]
ok i'll try it now

**Comment by zhwei8090** [comment]
@dfober  After testing, I found that there is still a problem, this is the test demo：
[demo.xml.zip](https://github.com/grame-cncm/libmusicxml/files/9006828/demo.xml.zip)

**Comment by dfober** [comment]
the flag to resolve collisions is not set: on the first staff you should add:
`\set<resolveMultiVoiceCollisions="on">`

**Comment by zhwei8090** [comment]
Still not right, I'll check again
```
{[ \staff<1> \set<autoHideTiedAccidentals="on"> \set<resolveMultiVoiceCollisions="on"> \accol<id=0, range="1-2"> \barFormat<style= "system", range="1-2"> 
   (* meas. 1 *)  \clef<"g2"> \key<-3> \meter<"2/4", autoBarlines="off", autoMeasuresNum="system"> \stemsUp \slurBegin:1<curve="up"> \beamBegin:1 b&1/8 \stemsUp \acc( a1/8)
 \slurEnd:1 \beamEnd:1 \stemsUp \beamBegin:1 a1/8 \stemsUp a1/8 \beamEnd:1 ]
 , 
[ \staff<1> \set<autoHideTiedAccidentals="on"> \set<resolveMultiVoiceCollisions="on"> \barFormat<style= "system", range="1"> 
   (* meas. 1 *)  \stemsDown \beamBegin:1 c1/16 \stemsDown e&1/16 \stemsDown \acc( g&1/16)
 \stemsDown f1/16 \beamEnd:1 \stemsDown \beamBegin:1 g&1/16 \stemsDown e&1/16 \stemsDown g&1/16 \stemsDown e&1/16 \beamEnd:1 ]
 , 
[ \staff<2> \set<autoHideTiedAccidentals="on"> \set<resolveMultiVoiceCollisions="on"> \barFormat<style= "system", range="2"> 
   (* meas. 1 *)  \staffFormat<distance=13> \clef<"f4"> \key<-3> \meter<"2/4", autoBarlines="off", autoMeasuresNum="system"> _/2 ]
  }

```

**Comment by zhwei8090** [comment]
The verification is ok, thank you

**Comment by dfober** [comment]
can I close you PR?

**Comment by zhwei8090** [comment]
Well, I'm closing it now, thanks a lot

**Pull request closed without merging**
